use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::env;
use std::ffi::{OsStr, OsString};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::metadata::{manifest_dir, Metadata, Package};
use crate::opt::ConnectOpts;
use crate::Config;
use anyhow::{bail, Context};
use console::style;
use proc_macro2::TokenStream;
use serde::{Deserialize, Serialize};
use sqlx::Connection;
use syn::parse::{Parse, ParseStream};
use syn::visit::Visit;
use syn::{Expr, ExprBinary, ExprGroup, ExprLit, ExprParen, Lit, LitStr, Macro, Token, Type};

pub struct PrepareCtx<'a> {
    pub config: &'a Config,
    pub workspace: bool,
    pub all: bool,
    pub assume_schema_unchanged: bool,
    pub cargo: OsString,
    pub cargo_args: Vec<String>,
    pub metadata: Metadata,
    pub connect_opts: ConnectOpts,
}

impl PrepareCtx<'_> {
    /// Path to the directory where cached queries should be placed.
    fn prepare_dir(&self) -> anyhow::Result<PathBuf> {
        if self.workspace {
            Ok(self.metadata.workspace_root().join(".sqlx"))
        } else {
            Ok(manifest_dir(&self.cargo)?.join(".sqlx"))
        }
    }

    fn query_manifest_path(&self) -> PathBuf {
        self.metadata
            .target_directory()
            .join("sqlx-prepare-manifest.json")
    }
}

pub async fn run(
    config: &Config,
    check: bool,
    all: bool,
    workspace: bool,
    assume_schema_unchanged: bool,
    connect_opts: ConnectOpts,
    cargo_args: Vec<String>,
) -> anyhow::Result<()> {
    let cargo = env::var_os("CARGO")
        .context("failed to get value of `CARGO`; `prepare` subcommand may only be invoked as `cargo sqlx prepare`")?;

    anyhow::ensure!(
        Path::new("Cargo.toml").exists(),
        r#"Failed to read `Cargo.toml`.
hint: This command only works in the manifest directory of a Cargo package or workspace."#
    );

    let metadata: Metadata = Metadata::from_current_directory(&cargo)?;
    let ctx = PrepareCtx {
        config,
        workspace,
        all,
        assume_schema_unchanged,
        cargo,
        cargo_args,
        metadata,
        connect_opts,
    };

    if check {
        prepare_check(&ctx).await
    } else {
        prepare(&ctx).await
    }
}

async fn prepare(ctx: &PrepareCtx<'_>) -> anyhow::Result<()> {
    if ctx.connect_opts.database_url.is_some() {
        check_backend(ctx.config, &ctx.connect_opts).await?;
    }

    let prepare_dir = ctx.prepare_dir()?;
    let cache_dir = ctx.metadata.target_directory().join("sqlx-prepare");
    run_prepare_step(ctx, &cache_dir)?;
    sync_query_data(&cache_dir, &prepare_dir)?;
    save_query_manifest(ctx)?;

    // Warn if no queries were generated. Glob since the directory may contain unrelated files.
    if glob_query_files(prepare_dir)?.is_empty() {
        println!("{} no queries found", style("warning:").yellow());
        return Ok(());
    }

    if ctx.workspace {
        println!(
            "query data written to .sqlx in the workspace root; \
             please check this into version control"
        );
    } else {
        println!(
            "query data written to .sqlx in the current directory; \
             please check this into version control"
        );
    }
    Ok(())
}

async fn prepare_check(ctx: &PrepareCtx<'_>) -> anyhow::Result<()> {
    if ctx.connect_opts.database_url.is_some() {
        check_backend(ctx.config, &ctx.connect_opts).await?;
    }

    // Re-generate and store the queries in a separate directory from both the prepared
    // queries and the ones generated by `cargo check`, to avoid conflicts.
    let prepare_dir = ctx.prepare_dir()?;
    let cache_dir = ctx.metadata.target_directory().join("sqlx-prepare-check");
    run_prepare_step(ctx, &cache_dir)?;

    // Compare .sqlx to cache.
    let prepare_filenames: HashSet<String> = glob_query_files(&prepare_dir)?
        .into_iter()
        .filter_map(|path| path.file_name().map(|f| f.to_string_lossy().into_owned()))
        .collect();
    let cache_filenames: HashSet<String> = glob_query_files(&cache_dir)?
        .into_iter()
        .filter_map(|path| path.file_name().map(|f| f.to_string_lossy().into_owned()))
        .collect();

    // Error: files in cache but not .sqlx.
    if cache_filenames
        .difference(&prepare_filenames)
        .next()
        .is_some()
    {
        bail!("prepare check failed: .sqlx is missing one or more queries; you should re-run sqlx prepare");
    }
    // Warn: files in .sqlx but not cache.
    if prepare_filenames
        .difference(&cache_filenames)
        .next()
        .is_some()
    {
        println!(
            "{} potentially unused queries found in .sqlx; you may want to re-run sqlx prepare",
            style("warning:").yellow()
        );
    }

    // Compare file contents as JSON to ignore superficial differences.
    // Everything in cache checked to be in .sqlx already.
    for filename in cache_filenames {
        let prepare_json = load_json_file(prepare_dir.join(&filename))?;
        let cache_json = load_json_file(cache_dir.join(&filename))?;
        if prepare_json != cache_json {
            bail!("prepare check failed: one or more query files differ ({}); you should re-run sqlx prepare", filename);
        }
    }

    Ok(())
}

fn run_prepare_step(ctx: &PrepareCtx, cache_dir: &Path) -> anyhow::Result<()> {
    // Create and/or clean the directory.
    fs::create_dir_all(cache_dir).context(format!(
        "Failed to create query cache directory: {:?}",
        cache_dir
    ))?;

    // Create directory to hold temporary query files before they get persisted to SQLX_OFFLINE_DIR
    let tmp_dir = ctx.metadata.target_directory().join("sqlx-tmp");
    fs::create_dir_all(&tmp_dir).context(format!(
        "Failed to create temporary query cache directory: {:?}",
        tmp_dir
    ))?;

    // Only delete sqlx-*.json files to avoid accidentally deleting any user data.
    for query_file in glob_query_files(cache_dir).context("Failed to read query cache files")? {
        fs::remove_file(&query_file)
            .with_context(|| format!("Failed to delete query file: {}", query_file.display()))?;
    }

    // Try only triggering a recompile on crates that use `sqlx-macros` falling back to a full
    // clean on error
    setup_minimal_project_recompile(ctx)?;

    // Compile the queries.
    let check_status = {
        let mut check_command = Command::new(&ctx.cargo);
        check_command
            .arg("check")
            .args(&ctx.cargo_args)
            .env("SQLX_TMP", tmp_dir)
            .env("SQLX_OFFLINE", "false")
            .env("SQLX_OFFLINE_DIR", cache_dir);

        if let Some(database_url) = &ctx.connect_opts.database_url {
            check_command.env("DATABASE_URL", database_url);
        }

        // `cargo check` recompiles on changed rust flags which can be set either via the env var
        // or through the `rustflags` field in `$CARGO_HOME/config` when the env var isn't set.
        // Because of this we only pass in `$RUSTFLAGS` when present.
        if let Ok(rustflags) = env::var("RUSTFLAGS") {
            check_command.env("RUSTFLAGS", rustflags);
        }

        check_command.status()?
    };
    if !check_status.success() {
        bail!("`cargo check` failed with status: {}", check_status);
    }

    Ok(())
}

fn sync_query_data(cache_dir: &Path, prepare_dir: &Path) -> anyhow::Result<()> {
    fs::create_dir_all(prepare_dir).context(format!(
        "Failed to create query cache directory: {:?}",
        prepare_dir
    ))?;

    let prepare_filenames: HashSet<String> = glob_query_files(prepare_dir)?
        .into_iter()
        .filter_map(|path| path.file_name().map(|f| f.to_string_lossy().into_owned()))
        .collect();
    let cache_filenames: HashSet<String> = glob_query_files(cache_dir)?
        .into_iter()
        .filter_map(|path| path.file_name().map(|f| f.to_string_lossy().into_owned()))
        .collect();

    for stale_filename in prepare_filenames.difference(&cache_filenames) {
        let stale_file = prepare_dir.join(stale_filename);
        fs::remove_file(&stale_file)
            .with_context(|| format!("Failed to delete query file: {}", stale_file.display()))?;
    }

    for filename in cache_filenames {
        let cache_file = cache_dir.join(&filename);
        let prepare_file = prepare_dir.join(&filename);

        let should_copy = match fs::read(&prepare_file) {
            Ok(prepare_bytes) => {
                let cache_json = load_json_file(&cache_file)?;
                let prepare_json: serde_json::Value = serde_json::from_slice(&prepare_bytes)?;
                prepare_json != cache_json
            }
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => true,
            Err(err) => {
                return Err(err).with_context(|| {
                    format!("failed to load file: {}", prepare_file.display())
                })
            }
        };

        if should_copy {
            fs::copy(&cache_file, &prepare_file).with_context(|| {
                format!(
                    "Failed to copy query file from {} to {}",
                    cache_file.display(),
                    prepare_file.display()
                )
            })?;
        }
    }

    Ok(())
}

#[derive(Debug, PartialEq)]
struct ProjectRecompileAction {
    // The names of the packages
    clean_packages: Vec<String>,
    touch_paths: Vec<PathBuf>,
}

#[derive(Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
struct QueryManifest {
    packages: BTreeMap<String, PackageQueries>,
}

#[derive(Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
struct PackageQueries {
    queries: Vec<String>,
}

/// Sets up recompiling only crates that depend on `sqlx-macros`
///
/// This gets a listing of all crates that depend on `sqlx-macros` (direct and transitive). The
/// crates within the current workspace have their source file's mtimes updated while crates
/// outside the workspace are selectively `cargo clean -p`ed. In this way we can trigger a
/// recompile of crates that may be using compile-time macros without forcing a full recompile.
///
/// If `workspace` is false, only the current package will have its files' mtimes updated.
fn setup_minimal_project_recompile(ctx: &PrepareCtx<'_>) -> anyhow::Result<()> {
    let changed_query_packages = if ctx.assume_schema_unchanged {
        match changed_query_package_dirs(ctx) {
            Ok(package_dirs) => Some(package_dirs),
            Err(err) => {
                println!(
                    "{} failed to detect changed query texts, falling back to full prepare behavior ({err})",
                    style("warning:").yellow()
                );
                None
            }
        }
    } else {
        None
    };

    let recompile_action: ProjectRecompileAction = if ctx.workspace {
        minimal_project_recompile_action(&ctx.metadata, ctx.all, changed_query_packages.as_ref())
    } else {
        current_package_recompile_action(
            &ctx.metadata,
            changed_query_packages.as_ref(),
            ctx.assume_schema_unchanged,
        )?
    };

    if let Err(err) = minimal_project_clean(&ctx.cargo, recompile_action) {
        println!(
            "Failed minimal recompile setup. Cleaning entire project. Err: {}",
            err
        );
        let clean_status = Command::new(&ctx.cargo).arg("clean").status()?;
        if !clean_status.success() {
            bail!("`cargo clean` failed with status: {}", clean_status);
        }
    }

    Ok(())
}

fn minimal_project_clean(
    cargo: impl AsRef<OsStr>,
    action: ProjectRecompileAction,
) -> anyhow::Result<()> {
    let ProjectRecompileAction {
        clean_packages,
        touch_paths,
    } = action;

    // Update the modified timestamp of package files to force a selective recompilation.
    for file in touch_paths {
        let now = filetime::FileTime::now();
        filetime::set_file_times(&file, now, now)
            .with_context(|| format!("Failed to update mtime for {file:?}"))?;
    }

    // Clean entire packages.
    for pkg_id in &clean_packages {
        let clean_status = Command::new(&cargo)
            .args(["clean", "-p", pkg_id])
            .status()?;

        if !clean_status.success() {
            bail!("`cargo clean -p {}` failed", pkg_id);
        }
    }

    Ok(())
}

fn current_package_recompile_action(
    metadata: &Metadata,
    changed_query_packages: Option<&BTreeSet<PathBuf>>,
    assume_schema_unchanged: bool,
) -> anyhow::Result<ProjectRecompileAction> {
    let package = metadata.current_package()
        .context("failed to get package in current working directory, pass `--workspace` if running from a workspace root")?;

    let should_touch = changed_query_packages
        .map(|packages| packages.contains(package.manifest_dir()))
        .unwrap_or(!assume_schema_unchanged);

    Ok(ProjectRecompileAction {
        clean_packages: Vec::new(),
        touch_paths: if should_touch {
            package.src_paths().to_vec()
        } else {
            Vec::new()
        },
    })
}

fn minimal_project_recompile_action(
    metadata: &Metadata,
    all: bool,
    changed_query_packages: Option<&BTreeSet<PathBuf>>,
) -> ProjectRecompileAction {
    // Get all the packages that depend on `sqlx-macros`
    let mut sqlx_macros_dependents = BTreeSet::new();
    let sqlx_macros_ids: BTreeSet<_> = metadata
        .entries()
        // We match just by name instead of name and url because some people may have it installed
        // through different means like vendoring
        .filter(|(_, package)| package.name() == "sqlx-macros")
        .map(|(id, _)| id)
        .collect();
    for sqlx_macros_id in sqlx_macros_ids {
        sqlx_macros_dependents.extend(metadata.all_dependents_of(sqlx_macros_id));
    }

    // Figure out which `sqlx-macros` dependents are in the workspace vs out
    let mut in_workspace_dependents = Vec::new();
    let mut out_of_workspace_dependents = Vec::new();
    for dependent in sqlx_macros_dependents {
        if metadata.workspace_members().contains(dependent) {
            in_workspace_dependents.push(dependent);
        } else {
            out_of_workspace_dependents.push(dependent);
        }
    }

    // In-workspace dependents have their source file's mtime updated.
    let files_to_touch: Vec<_> = in_workspace_dependents
        .iter()
        .filter_map(|id| {
            metadata.package(id).and_then(|package| {
                if changed_query_packages
                    .map(|packages| packages.contains(package.manifest_dir()))
                    .unwrap_or(true)
                {
                    Some(package.src_paths().to_owned())
                } else {
                    None
                }
            })
        })
        .flatten()
        .collect();

    // Out-of-workspace get `cargo clean -p <PKGID>`ed, only if --all is set.
    let packages_to_clean: Vec<_> = if all && changed_query_packages.is_none() {
        out_of_workspace_dependents
            .iter()
            .filter_map(|id| {
                metadata
                    .package(id)
                    .map(|package| package.name().to_owned())
            })
            // Do not clean sqlx, it depends on sqlx-macros but has no queries to prepare itself.
            .filter(|name| name != "sqlx")
            .collect()
    } else {
        Vec::new()
    };

    ProjectRecompileAction {
        clean_packages: packages_to_clean,
        touch_paths: files_to_touch,
    }
}

fn changed_query_package_dirs(ctx: &PrepareCtx<'_>) -> anyhow::Result<BTreeSet<PathBuf>> {
    let current_manifest = build_query_manifest(ctx)?;
    let previous_manifest = load_query_manifest(&ctx.query_manifest_path())?;

    let mut changed_package_dirs = BTreeSet::new();

    for (package_dir, package_queries) in &current_manifest.packages {
        if previous_manifest.packages.get(package_dir) != Some(package_queries) {
            changed_package_dirs.insert(PathBuf::from(package_dir));
        }
    }

    for package_dir in previous_manifest.packages.keys() {
        if !current_manifest.packages.contains_key(package_dir) {
            changed_package_dirs.insert(PathBuf::from(package_dir));
        }
    }

    Ok(changed_package_dirs)
}

fn save_query_manifest(ctx: &PrepareCtx<'_>) -> anyhow::Result<()> {
    let manifest = build_query_manifest(ctx)?;
    let manifest_path = ctx.query_manifest_path();
    let bytes = serde_json::to_vec_pretty(&manifest)?;

    fs::write(&manifest_path, bytes).with_context(|| {
        format!(
            "failed to write query manifest: {}",
            manifest_path.display()
        )
    })?;

    Ok(())
}

fn load_query_manifest(path: &Path) -> anyhow::Result<QueryManifest> {
    match fs::read(path) {
        Ok(bytes) => Ok(serde_json::from_slice(&bytes)?),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(QueryManifest::default()),
        Err(err) => Err(err)
            .with_context(|| format!("failed to read query manifest: {}", path.display())),
    }
}

fn build_query_manifest(ctx: &PrepareCtx<'_>) -> anyhow::Result<QueryManifest> {
    let mut packages = BTreeMap::new();

    if ctx.workspace {
        for package in sqlx_macro_workspace_packages(&ctx.metadata) {
            packages.insert(package_key(package), scan_package_queries(package)?);
        }
    } else {
        let package = ctx.metadata.current_package()
            .context("failed to get package in current working directory, pass `--workspace` if running from a workspace root")?;
        packages.insert(package_key(package), scan_package_queries(package)?);
    }

    Ok(QueryManifest { packages })
}

fn package_key(package: &Package) -> String {
    package.manifest_dir().to_string_lossy().into_owned()
}

fn sqlx_macro_workspace_packages(metadata: &Metadata) -> Vec<&Package> {
    let mut sqlx_macros_dependents = BTreeSet::new();
    let sqlx_macros_ids: BTreeSet<_> = metadata
        .entries()
        .filter(|(_, package)| package.name() == "sqlx-macros")
        .map(|(id, _)| id)
        .collect();

    for sqlx_macros_id in sqlx_macros_ids {
        sqlx_macros_dependents.extend(metadata.all_dependents_of(sqlx_macros_id));
    }

    sqlx_macros_dependents
        .into_iter()
        .filter(|id| metadata.workspace_members().contains(id))
        .filter_map(|id| metadata.package(id))
        .collect()
}

fn scan_package_queries(package: &Package) -> anyhow::Result<PackageQueries> {
    let mut queries = Vec::new();

    for rust_file in rust_files_in(package.manifest_dir())? {
        let source = fs::read_to_string(&rust_file)
            .with_context(|| format!("failed to read Rust source file: {}", rust_file.display()))?;
        let syntax = syn::parse_file(&source)
            .with_context(|| format!("failed to parse Rust source file: {}", rust_file.display()))?;

        let mut visitor = SqlxQueryVisitor::new(package.manifest_dir());
        visitor.visit_file(&syntax);
        queries.extend(visitor.finish()?);
    }

    queries.sort();
    queries.dedup();

    Ok(PackageQueries { queries })
}

fn rust_files_in(dir: &Path) -> anyhow::Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    let mut dirs = vec![dir.to_path_buf()];

    while let Some(path) = dirs.pop() {
        for entry in fs::read_dir(&path)
            .with_context(|| format!("failed to read directory: {}", path.display()))?
        {
            let entry = entry?;
            let entry_path = entry.path();
            let file_type = entry.file_type()?;

            if file_type.is_dir() {
                if entry.file_name() == OsStr::new("target") {
                    continue;
                }

                dirs.push(entry_path);
            } else if file_type.is_file()
                && entry_path.extension().is_some_and(|ext| ext == OsStr::new("rs"))
            {
                files.push(entry_path);
            }
        }
    }

    files.sort();
    Ok(files)
}

struct SqlxQueryVisitor<'a> {
    package_dir: &'a Path,
    queries: Vec<String>,
    error: Option<anyhow::Error>,
}

impl<'a> SqlxQueryVisitor<'a> {
    fn new(package_dir: &'a Path) -> Self {
        Self {
            package_dir,
            queries: Vec::new(),
            error: None,
        }
    }

    fn finish(self) -> anyhow::Result<Vec<String>> {
        if let Some(err) = self.error {
            Err(err)
        } else {
            Ok(self.queries)
        }
    }
}

impl Visit<'_> for SqlxQueryVisitor<'_> {
    fn visit_macro(&mut self, mac: &Macro) {
        if self.error.is_none() {
            match extract_query_text(mac, self.package_dir) {
                Ok(Some(query)) => self.queries.push(query),
                Ok(None) => {}
                Err(err) => self.error = Some(err),
            }
        }

        syn::visit::visit_macro(self, mac);
    }
}

fn extract_query_text(mac: &Macro, package_dir: &Path) -> anyhow::Result<Option<String>> {
    let Some(ident) = mac.path.segments.last().map(|segment| segment.ident.to_string()) else {
        return Ok(None);
    };

    match ident.as_str() {
        "query" | "query_unchecked" | "query_scalar" | "query_scalar_unchecked" => {
            let args: QueryMacroArgs = syn::parse2(mac.tokens.clone()).with_context(|| {
                format!("failed to parse macro arguments for `{ident}!`")
            })?;
            Ok(eval_string_expr(&args.query))
        }
        "query_as" | "query_as_unchecked" => {
            let args: QueryAsMacroArgs = syn::parse2(mac.tokens.clone()).with_context(|| {
                format!("failed to parse macro arguments for `{ident}!`")
            })?;
            Ok(eval_string_expr(&args.query))
        }
        "query_file"
        | "query_file_unchecked"
        | "query_file_scalar"
        | "query_file_scalar_unchecked" => {
            let args: QueryFileMacroArgs = syn::parse2(mac.tokens.clone()).with_context(|| {
                format!("failed to parse macro arguments for `{ident}!`")
            })?;
            Ok(Some(read_query_file(package_dir, &args.path)?))
        }
        "query_file_as" | "query_file_as_unchecked" => {
            let args: QueryFileAsMacroArgs = syn::parse2(mac.tokens.clone()).with_context(|| {
                format!("failed to parse macro arguments for `{ident}!`")
            })?;
            Ok(Some(read_query_file(package_dir, &args.path)?))
        }
        _ => Ok(None),
    }
}

fn read_query_file(package_dir: &Path, path: &LitStr) -> anyhow::Result<String> {
    let query_path = package_dir.join(path.value());
    fs::read_to_string(&query_path)
        .with_context(|| format!("failed to read SQL query file: {}", query_path.display()))
}

fn eval_string_expr(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Lit(ExprLit {
            lit: Lit::Str(lit_str),
            ..
        }) => Some(lit_str.value()),
        Expr::Binary(ExprBinary {
            left,
            op: syn::BinOp::Add(_),
            right,
            ..
        }) => Some(format!("{}{}", eval_string_expr(left)?, eval_string_expr(right)?)),
        Expr::Group(ExprGroup { expr, .. }) | Expr::Paren(ExprParen { expr, .. }) => {
            eval_string_expr(expr)
        }
        _ => None,
    }
}

struct QueryMacroArgs {
    query: Expr,
}

impl Parse for QueryMacroArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let query = input.parse()?;
        let _ = input.parse::<Option<Token![,]>>()?;
        let _rest: TokenStream = input.parse()?;
        Ok(Self { query })
    }
}

struct QueryAsMacroArgs {
    _record: Type,
    query: Expr,
}

impl Parse for QueryAsMacroArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let record = input.parse()?;
        let _comma = input.parse::<Token![,]>()?;
        let query = input.parse()?;
        let _ = input.parse::<Option<Token![,]>>()?;
        let _rest: TokenStream = input.parse()?;
        Ok(Self {
            _record: record,
            query,
        })
    }
}

struct QueryFileMacroArgs {
    path: LitStr,
}

impl Parse for QueryFileMacroArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let path = input.parse()?;
        let _ = input.parse::<Option<Token![,]>>()?;
        let _rest: TokenStream = input.parse()?;
        Ok(Self { path })
    }
}

struct QueryFileAsMacroArgs {
    _record: Type,
    path: LitStr,
}

impl Parse for QueryFileAsMacroArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let record = input.parse()?;
        let _comma = input.parse::<Token![,]>()?;
        let path = input.parse()?;
        let _ = input.parse::<Option<Token![,]>>()?;
        let _rest: TokenStream = input.parse()?;
        Ok(Self {
            _record: record,
            path,
        })
    }
}

/// Find all `query-*.json` files in a directory.
fn glob_query_files(path: impl AsRef<Path>) -> anyhow::Result<Vec<PathBuf>> {
    let path = path.as_ref();
    let pattern = path.join("query-*.json");
    glob::glob(
        pattern
            .to_str()
            .context("query cache path is invalid UTF-8")?,
    )
    .with_context(|| format!("failed to read query cache path: {}", path.display()))?
    .collect::<Result<Vec<_>, _>>()
    .context("glob failed")
}

/// Load the JSON contents of a query data file.
fn load_json_file(path: impl AsRef<Path>) -> anyhow::Result<serde_json::Value> {
    let path = path.as_ref();
    let file_bytes =
        fs::read(path).with_context(|| format!("failed to load file: {}", path.display()))?;
    Ok(serde_json::from_slice(&file_bytes)?)
}

async fn check_backend(config: &Config, opts: &ConnectOpts) -> anyhow::Result<()> {
    crate::connect(config, opts).await?.close().await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::assert_eq;

    #[test]
    fn minimal_project_recompile_action_works() -> anyhow::Result<()> {
        let sample_metadata_path = Path::new("tests")
            .join("assets")
            .join("sample_metadata.json");
        let sample_metadata = std::fs::read_to_string(sample_metadata_path)?;
        let metadata: Metadata = sample_metadata.parse()?;

        let action = minimal_project_recompile_action(&metadata, false, None);
        assert_eq!(
            action,
            ProjectRecompileAction {
                clean_packages: vec![],
                touch_paths: vec![
                    "/home/user/problematic/workspace/b_in_workspace_lib/src/lib.rs".into(),
                    "/home/user/problematic/workspace/c_in_workspace_bin/src/main.rs".into(),
                ],
            }
        );

        Ok(())
    }

    #[test]
    fn eval_string_expr_handles_literal_concat() -> anyhow::Result<()> {
        let expr: Expr = syn::parse_str("\"SELECT \" + \"1\"")?;
        assert_eq!(eval_string_expr(&expr), Some("SELECT 1".to_string()));
        Ok(())
    }

    #[test]
    fn extract_query_text_reads_query_file_macro() -> anyhow::Result<()> {
        let tempdir = tempfile::tempdir()?;
        let sql_path = tempdir.path().join("query.sql");
        fs::write(&sql_path, "select 1")?;

        let mac: Macro = syn::parse_str("query_file!(\"query.sql\")")?;
        assert_eq!(
            extract_query_text(&mac, tempdir.path())?,
            Some("select 1".to_string())
        );
        Ok(())
    }
}
