use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::env;
use std::ffi::{OsStr, OsString};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::metadata::{manifest_dir, Metadata, Package};
use crate::opt::ConnectOpts;
use crate::Config;
use anyhow::{bail, Context};
use console::style;
use proc_macro2::TokenStream;
use serde::{Deserialize, Serialize};
use sqlx::{Connection, Row};
use syn::parse::{Parse, ParseStream};
use syn::visit::Visit;
use syn::{Expr, ExprBinary, ExprGroup, ExprLit, ExprParen, Lit, LitStr, Macro, Token, Type};

pub struct PrepareCtx<'a> {
    pub config: &'a Config,
    pub workspace: bool,
    pub all: bool,
    pub detect_query_changes: bool,
    pub detect_schema_changes: bool,
    pub verbose: bool,
    pub cargo: OsString,
    pub cargo_args: Vec<String>,
    pub metadata: Metadata,
    pub connect_opts: ConnectOpts,
}

impl PrepareCtx<'_> {
    /// Path to the directory where cached queries should be placed.
    fn prepare_dir(&self) -> anyhow::Result<PathBuf> {
        if self.workspace {
            Ok(self.metadata.workspace_root().join(".sqlx"))
        } else {
            Ok(manifest_dir(&self.cargo)?.join(".sqlx"))
        }
    }

    fn query_manifest_path(&self) -> PathBuf {
        self.metadata
            .target_directory()
            .join("sqlx-prepare-manifest.json")
    }
}

pub async fn run(
    config: &Config,
    check: bool,
    all: bool,
    workspace: bool,
    detect_query_changes: bool,
    detect_schema_changes: bool,
    verbose: bool,
    connect_opts: ConnectOpts,
    cargo_args: Vec<String>,
) -> anyhow::Result<()> {
    let cargo = env::var_os("CARGO")
        .context("failed to get value of `CARGO`; `prepare` subcommand may only be invoked as `cargo sqlx prepare`")?;

    anyhow::ensure!(
        Path::new("Cargo.toml").exists(),
        r#"Failed to read `Cargo.toml`.
hint: This command only works in the manifest directory of a Cargo package or workspace."#
    );

    let metadata: Metadata = Metadata::from_current_directory(&cargo)?;
    let ctx = PrepareCtx {
        config,
        workspace,
        all,
        detect_query_changes,
        detect_schema_changes,
        verbose,
        cargo,
        cargo_args,
        metadata,
        connect_opts,
    };

    if check {
        prepare_check(&ctx).await
    } else {
        prepare(&ctx).await
    }
}

async fn prepare(ctx: &PrepareCtx<'_>) -> anyhow::Result<()> {
    if ctx.connect_opts.database_url.is_some() {
        check_backend(ctx.config, &ctx.connect_opts).await?;
    }

    let previous_manifest = load_query_manifest(&ctx.query_manifest_path())?;
    let current_manifest = build_query_manifest(ctx).await?;
    let selection = if ctx.detect_query_changes || ctx.detect_schema_changes {
        match select_changed_packages(ctx, &current_manifest, &previous_manifest) {
            Ok(selection) => Some(selection),
            Err(err) => {
                println!(
                    "{} failed to detect changed packages, falling back to full prepare behavior ({err})",
                    style("warning:").yellow()
                );
                None
            }
        }
    } else {
        None
    };

    if ctx.verbose {
        print_verbose_selection(ctx, selection.as_ref());
    }

    if selection.as_ref().is_some_and(|selection| selection.packages.is_empty()) {
        save_query_manifest(ctx, &current_manifest)?;
        println!("{}; skipping recompilation", unchanged_reason(ctx));
        return Ok(());
    }

    let prepare_dir = ctx.prepare_dir()?;
    let cache_dir = ctx.metadata.target_directory().join("sqlx-prepare");
    run_prepare_step(ctx, &cache_dir, selection.as_ref().map(|selection| &selection.packages))?;
    sync_query_data(
        &cache_dir,
        &prepare_dir,
        &previous_manifest,
        &current_manifest,
        selection.as_ref().map(|selection| &selection.packages),
    )?;
    save_query_manifest(ctx, &current_manifest)?;

    // Warn if no queries were generated. Glob since the directory may contain unrelated files.
    if glob_query_files(prepare_dir)?.is_empty() {
        println!("{} no queries found", style("warning:").yellow());
        return Ok(());
    }

    if ctx.workspace {
        println!(
            "query data written to .sqlx in the workspace root; \
             please check this into version control"
        );
    } else {
        println!(
            "query data written to .sqlx in the current directory; \
             please check this into version control"
        );
    }
    Ok(())
}

async fn prepare_check(ctx: &PrepareCtx<'_>) -> anyhow::Result<()> {
    if ctx.connect_opts.database_url.is_some() {
        check_backend(ctx.config, &ctx.connect_opts).await?;
    }

    // Re-generate and store the queries in a separate directory from both the prepared
    // queries and the ones generated by `cargo check`, to avoid conflicts.
    let prepare_dir = ctx.prepare_dir()?;
    let cache_dir = ctx.metadata.target_directory().join("sqlx-prepare-check");
    run_prepare_step(ctx, &cache_dir, None)?;

    // Compare .sqlx to cache.
    let prepare_filenames: HashSet<String> = glob_query_files(&prepare_dir)?
        .into_iter()
        .filter_map(|path| path.file_name().map(|f| f.to_string_lossy().into_owned()))
        .collect();
    let cache_filenames: HashSet<String> = glob_query_files(&cache_dir)?
        .into_iter()
        .filter_map(|path| path.file_name().map(|f| f.to_string_lossy().into_owned()))
        .collect();

    // Error: files in cache but not .sqlx.
    if cache_filenames
        .difference(&prepare_filenames)
        .next()
        .is_some()
    {
        bail!("prepare check failed: .sqlx is missing one or more queries; you should re-run sqlx prepare");
    }
    // Warn: files in .sqlx but not cache.
    if prepare_filenames
        .difference(&cache_filenames)
        .next()
        .is_some()
    {
        println!(
            "{} potentially unused queries found in .sqlx; you may want to re-run sqlx prepare",
            style("warning:").yellow()
        );
    }

    // Compare file contents as JSON to ignore superficial differences.
    // Everything in cache checked to be in .sqlx already.
    for filename in cache_filenames {
        let prepare_json = load_json_file(prepare_dir.join(&filename))?;
        let cache_json = load_json_file(cache_dir.join(&filename))?;
        if prepare_json != cache_json {
            bail!("prepare check failed: one or more query files differ ({}); you should re-run sqlx prepare", filename);
        }
    }

    Ok(())
}

fn run_prepare_step(
    ctx: &PrepareCtx,
    cache_dir: &Path,
    touched_packages: Option<&BTreeSet<PathBuf>>,
) -> anyhow::Result<()> {
    // Create and/or clean the directory.
    fs::create_dir_all(cache_dir).context(format!(
        "Failed to create query cache directory: {:?}",
        cache_dir
    ))?;

    // Create directory to hold temporary query files before they get persisted to SQLX_OFFLINE_DIR
    let tmp_dir = ctx.metadata.target_directory().join("sqlx-tmp");
    fs::create_dir_all(&tmp_dir).context(format!(
        "Failed to create temporary query cache directory: {:?}",
        tmp_dir
    ))?;

    // Only delete sqlx-*.json files to avoid accidentally deleting any user data.
    for query_file in glob_query_files(cache_dir).context("Failed to read query cache files")? {
        fs::remove_file(&query_file)
            .with_context(|| format!("Failed to delete query file: {}", query_file.display()))?;
    }

    // Try only triggering a recompile on crates that use `sqlx-macros` falling back to a full
    // clean on error
    setup_minimal_project_recompile(ctx, touched_packages)?;

    // Compile the queries.
    let check_status = {
        let mut check_command = Command::new(&ctx.cargo);
        check_command
            .arg("check")
            .args(&ctx.cargo_args)
            .env("SQLX_TMP", tmp_dir)
            .env("SQLX_OFFLINE", "false")
            .env("SQLX_OFFLINE_DIR", cache_dir);

        if let Some(database_url) = &ctx.connect_opts.database_url {
            check_command.env("DATABASE_URL", database_url);
        }

        // `cargo check` recompiles on changed rust flags which can be set either via the env var
        // or through the `rustflags` field in `$CARGO_HOME/config` when the env var isn't set.
        // Because of this we only pass in `$RUSTFLAGS` when present.
        if let Ok(rustflags) = env::var("RUSTFLAGS") {
            check_command.env("RUSTFLAGS", rustflags);
        }

        check_command.status()?
    };
    if !check_status.success() {
        bail!("`cargo check` failed with status: {}", check_status);
    }

    Ok(())
}

fn sync_query_data(
    cache_dir: &Path,
    prepare_dir: &Path,
    previous_manifest: &QueryManifest,
    current_manifest: &QueryManifest,
    touched_packages: Option<&BTreeSet<PathBuf>>,
) -> anyhow::Result<()> {
    fs::create_dir_all(prepare_dir).context(format!(
        "Failed to create query cache directory: {:?}",
        prepare_dir
    ))?;

    let cache_filenames: HashSet<String> = glob_query_files(cache_dir)?
        .into_iter()
        .filter_map(|path| path.file_name().map(|f| f.to_string_lossy().into_owned()))
        .collect();

    let stale_filenames: HashSet<String> = if let Some(touched_packages) = touched_packages {
        touched_query_hashes(previous_manifest, touched_packages)
            .difference(&touched_query_hashes(current_manifest, touched_packages))
            .map(|hash| format!("query-{hash}.json"))
            .collect()
    } else {
        let prepare_filenames: HashSet<String> = glob_query_files(prepare_dir)?
            .into_iter()
            .filter_map(|path| path.file_name().map(|f| f.to_string_lossy().into_owned()))
            .collect();
        prepare_filenames
            .difference(&cache_filenames)
            .cloned()
            .collect()
    };

    for stale_filename in stale_filenames {
        let stale_file = prepare_dir.join(stale_filename);
        if stale_file.exists() {
            fs::remove_file(&stale_file).with_context(|| {
                format!("Failed to delete query file: {}", stale_file.display())
            })?;
        }
    }

    for filename in cache_filenames {
        let cache_file = cache_dir.join(&filename);
        let prepare_file = prepare_dir.join(&filename);

        let should_copy = match fs::read(&prepare_file) {
            Ok(prepare_bytes) => {
                let cache_json = load_json_file(&cache_file)?;
                let prepare_json: serde_json::Value = serde_json::from_slice(&prepare_bytes)?;
                prepare_json != cache_json
            }
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => true,
            Err(err) => {
                return Err(err).with_context(|| {
                    format!("failed to load file: {}", prepare_file.display())
                })
            }
        };

        if should_copy {
            fs::copy(&cache_file, &prepare_file).with_context(|| {
                format!(
                    "Failed to copy query file from {} to {}",
                    cache_file.display(),
                    prepare_file.display()
                )
            })?;
        }
    }

    Ok(())
}

#[derive(Debug, PartialEq)]
struct ProjectRecompileAction {
    // The names of the packages
    clean_packages: Vec<String>,
    touch_paths: Vec<PathBuf>,
}

#[derive(Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(default)]
struct QueryManifest {
    packages: BTreeMap<String, PackageQueries>,
    postgres_schema: Option<PostgresSchemaSnapshot>,
}

#[derive(Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(default)]
struct PackageQueries {
    queries: Vec<String>,
    dependencies: Vec<String>,
}

#[derive(Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(default)]
struct PostgresSchemaSnapshot {
    objects: BTreeMap<String, String>,
}

#[derive(Debug, Default)]
struct PackageSelection {
    packages: BTreeSet<PathBuf>,
    query_changed_packages: BTreeSet<PathBuf>,
    schema_changed_packages: BTreeSet<PathBuf>,
    changed_schema_objects: BTreeSet<String>,
}

/// Sets up recompiling only crates that depend on `sqlx-macros`
///
/// This gets a listing of all crates that depend on `sqlx-macros` (direct and transitive). The
/// crates within the current workspace have their source file's mtimes updated while crates
/// outside the workspace are selectively `cargo clean -p`ed. In this way we can trigger a
/// recompile of crates that may be using compile-time macros without forcing a full recompile.
///
/// If `workspace` is false, only the current package will have its files' mtimes updated.
fn setup_minimal_project_recompile(
    ctx: &PrepareCtx<'_>,
    changed_packages: Option<&BTreeSet<PathBuf>>,
) -> anyhow::Result<()> {
    let recompile_action: ProjectRecompileAction = if ctx.workspace {
        minimal_project_recompile_action(&ctx.metadata, ctx.all, changed_packages)
    } else {
        current_package_recompile_action(&ctx.metadata, changed_packages)?
    };

    if let Err(err) = minimal_project_clean(&ctx.cargo, recompile_action) {
        println!(
            "Failed minimal recompile setup. Cleaning entire project. Err: {}",
            err
        );
        let clean_status = Command::new(&ctx.cargo).arg("clean").status()?;
        if !clean_status.success() {
            bail!("`cargo clean` failed with status: {}", clean_status);
        }
    }

    Ok(())
}

fn minimal_project_clean(
    cargo: impl AsRef<OsStr>,
    action: ProjectRecompileAction,
) -> anyhow::Result<()> {
    let ProjectRecompileAction {
        clean_packages,
        touch_paths,
    } = action;

    // Update the modified timestamp of package files to force a selective recompilation.
    for file in touch_paths {
        let now = filetime::FileTime::now();
        filetime::set_file_times(&file, now, now)
            .with_context(|| format!("Failed to update mtime for {file:?}"))?;
    }

    // Clean entire packages.
    for pkg_id in &clean_packages {
        let clean_status = Command::new(&cargo)
            .args(["clean", "-p", pkg_id])
            .status()?;

        if !clean_status.success() {
            bail!("`cargo clean -p {}` failed", pkg_id);
        }
    }

    Ok(())
}

fn current_package_recompile_action(
    metadata: &Metadata,
    changed_query_packages: Option<&BTreeSet<PathBuf>>,
) -> anyhow::Result<ProjectRecompileAction> {
    let package = metadata.current_package()
        .context("failed to get package in current working directory, pass `--workspace` if running from a workspace root")?;

    let should_touch = changed_query_packages
        .map(|packages| packages.contains(package.manifest_dir()))
        .unwrap_or(true);

    Ok(ProjectRecompileAction {
        clean_packages: Vec::new(),
        touch_paths: if should_touch {
            package.src_paths().to_vec()
        } else {
            Vec::new()
        },
    })
}

fn minimal_project_recompile_action(
    metadata: &Metadata,
    all: bool,
    changed_query_packages: Option<&BTreeSet<PathBuf>>,
) -> ProjectRecompileAction {
    // Get all the packages that depend on `sqlx-macros`
    let mut sqlx_macros_dependents = BTreeSet::new();
    let sqlx_macros_ids: BTreeSet<_> = metadata
        .entries()
        // We match just by name instead of name and url because some people may have it installed
        // through different means like vendoring
        .filter(|(_, package)| package.name() == "sqlx-macros")
        .map(|(id, _)| id)
        .collect();
    for sqlx_macros_id in sqlx_macros_ids {
        sqlx_macros_dependents.extend(metadata.all_dependents_of(sqlx_macros_id));
    }

    // Figure out which `sqlx-macros` dependents are in the workspace vs out
    let mut in_workspace_dependents = Vec::new();
    let mut out_of_workspace_dependents = Vec::new();
    for dependent in sqlx_macros_dependents {
        if metadata.workspace_members().contains(dependent) {
            in_workspace_dependents.push(dependent);
        } else {
            out_of_workspace_dependents.push(dependent);
        }
    }

    // In-workspace dependents have their source file's mtime updated.
    let files_to_touch: Vec<_> = in_workspace_dependents
        .iter()
        .filter_map(|id| {
            metadata.package(id).and_then(|package| {
                if changed_query_packages
                    .map(|packages| packages.contains(package.manifest_dir()))
                    .unwrap_or(true)
                {
                    Some(package.src_paths().to_owned())
                } else {
                    None
                }
            })
        })
        .flatten()
        .collect();

    // Out-of-workspace get `cargo clean -p <PKGID>`ed, only if --all is set.
    let packages_to_clean: Vec<_> = if all && changed_query_packages.is_none() {
        out_of_workspace_dependents
            .iter()
            .filter_map(|id| {
                metadata
                    .package(id)
                    .map(|package| package.name().to_owned())
            })
            // Do not clean sqlx, it depends on sqlx-macros but has no queries to prepare itself.
            .filter(|name| name != "sqlx")
            .collect()
    } else {
        Vec::new()
    };

    ProjectRecompileAction {
        clean_packages: packages_to_clean,
        touch_paths: files_to_touch,
    }
}

fn select_changed_packages(
    ctx: &PrepareCtx<'_>,
    current_manifest: &QueryManifest,
    previous_manifest: &QueryManifest,
) -> anyhow::Result<PackageSelection> {
    if previous_manifest.packages.is_empty() {
        let query_changed_packages = if ctx.detect_query_changes {
            current_manifest
                .packages
                .keys()
                .map(PathBuf::from)
                .collect()
        } else {
            BTreeSet::new()
        };
        let schema_changed_packages = if ctx.detect_schema_changes {
            current_manifest
                .packages
                .keys()
                .map(PathBuf::from)
                .collect()
        } else {
            BTreeSet::new()
        };
        let mut packages = query_changed_packages.clone();
        packages.extend(schema_changed_packages.iter().cloned());
        return Ok(PackageSelection {
            query_changed_packages,
            schema_changed_packages,
            packages,
            ..Default::default()
        });
    }

    let query_changed_packages = if ctx.detect_query_changes {
        query_changed_package_dirs(current_manifest, previous_manifest)
    } else {
        BTreeSet::new()
    };
    let mut packages = query_changed_packages.clone();
    let mut schema_changed_packages = BTreeSet::new();
    let mut changed_schema_objects = BTreeSet::new();

    if ctx.detect_schema_changes {
        let schema_changes = schema_affected_package_dirs(current_manifest, previous_manifest)?;
        changed_schema_objects = schema_changes.changed_objects;
        schema_changed_packages = schema_changes.packages;

        for package_dir in &schema_changed_packages {
            packages.insert(package_dir.clone());
        }
    }

    Ok(PackageSelection {
        packages,
        query_changed_packages,
        schema_changed_packages,
        changed_schema_objects,
    })
}

fn query_changed_package_dirs(
    current_manifest: &QueryManifest,
    previous_manifest: &QueryManifest,
) -> BTreeSet<PathBuf> {
    let mut changed_package_dirs = BTreeSet::new();

    for (package_dir, package_queries) in &current_manifest.packages {
        if previous_manifest.packages.get(package_dir).map(|pkg| &pkg.queries) != Some(&package_queries.queries) {
            changed_package_dirs.insert(PathBuf::from(package_dir));
        }
    }

    for package_dir in previous_manifest.packages.keys() {
        if !current_manifest.packages.contains_key(package_dir) {
            changed_package_dirs.insert(PathBuf::from(package_dir));
        }
    }

    changed_package_dirs
}

#[derive(Debug, Default)]
struct SchemaAffectedPackages {
    packages: BTreeSet<PathBuf>,
    changed_objects: BTreeSet<String>,
}

fn schema_affected_package_dirs(
    current_manifest: &QueryManifest,
    previous_manifest: &QueryManifest,
) -> anyhow::Result<SchemaAffectedPackages> {
    let Some(previous_schema) = &previous_manifest.postgres_schema else {
        return Ok(SchemaAffectedPackages::default());
    };
    let Some(current_schema) = &current_manifest.postgres_schema else {
        return Ok(SchemaAffectedPackages::default());
    };

    let changed_objects = changed_postgres_objects(previous_schema, current_schema);
    if changed_objects.is_empty() {
        return Ok(SchemaAffectedPackages::default());
    }

    let packages = current_manifest
        .packages
        .iter()
        .filter(|(_, package)| package.dependencies.iter().any(|dep| changed_objects.contains(dep)))
        .map(|(package_dir, _)| PathBuf::from(package_dir))
        .collect();

    Ok(SchemaAffectedPackages {
        packages,
        changed_objects,
    })
}

fn print_verbose_selection(ctx: &PrepareCtx<'_>, selection: Option<&PackageSelection>) {
    println!("prepare verbose:");
    println!("  workspace: {}", ctx.workspace);
    println!("  detect-query-changes: {}", ctx.detect_query_changes);
    println!("  detect-schema-changes: {}", ctx.detect_schema_changes);

    match selection {
        None => {
            println!("  path: full prepare");
        }
        Some(selection) => {
            println!("  path: selective prepare");
            println!(
                "  packages selected: {}",
                selection.packages.len()
            );

            if !selection.query_changed_packages.is_empty() {
                println!("  query text changes:");
                for package in &selection.query_changed_packages {
                    println!("    {}", package.display());
                }
            }

            if ctx.detect_schema_changes {
                println!(
                    "  schema objects changed: {}",
                    selection.changed_schema_objects.len()
                );
                for object in &selection.changed_schema_objects {
                    println!("    {}", object);
                }

                if !selection.schema_changed_packages.is_empty() {
                    println!("  packages selected by schema changes:");
                    for package in &selection.schema_changed_packages {
                        println!("    {}", package.display());
                    }
                }
            }

            if selection.packages.is_empty() {
                println!("  no packages selected");
            } else {
                println!("  final package set:");
                for package in &selection.packages {
                    println!("    {}", package.display());
                }
            }
        }
    }
}

fn unchanged_reason(ctx: &PrepareCtx<'_>) -> &'static str {
    match (ctx.detect_query_changes, ctx.detect_schema_changes) {
        (true, true) => "query and schema data unchanged",
        (true, false) => "query data unchanged",
        (false, true) => "schema data unchanged",
        (false, false) => "query data unchanged",
    }
}

fn save_query_manifest(ctx: &PrepareCtx<'_>, manifest: &QueryManifest) -> anyhow::Result<()> {
    let manifest_path = ctx.query_manifest_path();
    let bytes = serde_json::to_vec_pretty(&manifest)?;

    fs::write(&manifest_path, bytes).with_context(|| {
        format!(
            "failed to write query manifest: {}",
            manifest_path.display()
        )
    })?;

    Ok(())
}

fn load_query_manifest(path: &Path) -> anyhow::Result<QueryManifest> {
    match fs::read(path) {
        Ok(bytes) => Ok(serde_json::from_slice(&bytes)?),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(QueryManifest::default()),
        Err(err) => Err(err)
            .with_context(|| format!("failed to read query manifest: {}", path.display())),
    }
}

async fn build_query_manifest(ctx: &PrepareCtx<'_>) -> anyhow::Result<QueryManifest> {
    let mut packages = BTreeMap::new();

    if ctx.workspace {
        for package in sqlx_macro_workspace_packages(&ctx.metadata) {
            packages.insert(package_key(package), scan_package_queries(package)?);
        }
    } else {
        let package = ctx.metadata.current_package()
            .context("failed to get package in current working directory, pass `--workspace` if running from a workspace root")?;
        packages.insert(package_key(package), scan_package_queries(package)?);
    }

    Ok(QueryManifest {
        packages,
        postgres_schema: if ctx.detect_schema_changes {
            fetch_postgres_schema_snapshot(ctx).await?
        } else {
            None
        },
    })
}

fn package_key(package: &Package) -> String {
    package.manifest_dir().to_string_lossy().into_owned()
}

fn sqlx_macro_workspace_packages(metadata: &Metadata) -> Vec<&Package> {
    let mut sqlx_macros_dependents = BTreeSet::new();
    let sqlx_macros_ids: BTreeSet<_> = metadata
        .entries()
        .filter(|(_, package)| package.name() == "sqlx-macros")
        .map(|(id, _)| id)
        .collect();

    for sqlx_macros_id in sqlx_macros_ids {
        sqlx_macros_dependents.extend(metadata.all_dependents_of(sqlx_macros_id));
    }

    sqlx_macros_dependents
        .into_iter()
        .filter(|id| metadata.workspace_members().contains(id))
        .filter_map(|id| metadata.package(id))
        .collect()
}

fn scan_package_queries(package: &Package) -> anyhow::Result<PackageQueries> {
    let mut queries = BTreeSet::new();
    let mut dependencies = BTreeSet::new();

    for rust_file in rust_files_in(package.manifest_dir())? {
        let source = fs::read_to_string(&rust_file)
            .with_context(|| format!("failed to read Rust source file: {}", rust_file.display()))?;
        let syntax = syn::parse_file(&source)
            .with_context(|| format!("failed to parse Rust source file: {}", rust_file.display()))?;

        let mut visitor = SqlxQueryVisitor::new(package.manifest_dir());
        visitor.visit_file(&syntax);
        for query in visitor.finish()? {
            queries.insert(hash_query_text(&query));
            dependencies.extend(extract_sql_dependencies(&query));
        }
    }

    Ok(PackageQueries {
        queries: queries.into_iter().collect(),
        dependencies: dependencies.into_iter().collect(),
    })
}

fn hash_query_text(query: &str) -> String {
    use sha2::{Digest, Sha256};

    hex::encode(Sha256::digest(query.as_bytes()))
}

fn touched_query_hashes(
    manifest: &QueryManifest,
    touched_packages: &BTreeSet<PathBuf>,
) -> HashSet<String> {
    manifest
        .packages
        .iter()
        .filter(|(package_dir, _)| touched_packages.contains(&PathBuf::from(package_dir.as_str())))
        .flat_map(|(_, package)| package.queries.iter().cloned())
        .collect()
}

fn changed_postgres_objects(
    previous_schema: &PostgresSchemaSnapshot,
    current_schema: &PostgresSchemaSnapshot,
) -> BTreeSet<String> {
    let mut changed = BTreeSet::new();

    for (name, signature) in &current_schema.objects {
        if previous_schema.objects.get(name) != Some(signature) {
            changed.extend(expand_postgres_object_aliases(name));
        }
    }

    for name in previous_schema.objects.keys() {
        if !current_schema.objects.contains_key(name) {
            changed.extend(expand_postgres_object_aliases(name));
        }
    }

    changed
}

fn expand_postgres_object_aliases(name: &str) -> BTreeSet<String> {
    let mut aliases = BTreeSet::from([name.to_string()]);
    if let Some((kind, qualified_name)) = name.split_once(':') {
        if let Some((_, object_name)) = qualified_name.rsplit_once('.') {
            aliases.insert(format!("{kind}:{object_name}"));
        }
    }
    aliases
}

fn rust_files_in(dir: &Path) -> anyhow::Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    let mut dirs = vec![dir.to_path_buf()];

    while let Some(path) = dirs.pop() {
        for entry in fs::read_dir(&path)
            .with_context(|| format!("failed to read directory: {}", path.display()))?
        {
            let entry = entry?;
            let entry_path = entry.path();
            let file_type = entry.file_type()?;

            if file_type.is_dir() {
                if entry.file_name() == OsStr::new("target") {
                    continue;
                }

                dirs.push(entry_path);
            } else if file_type.is_file()
                && entry_path.extension().is_some_and(|ext| ext == OsStr::new("rs"))
            {
                files.push(entry_path);
            }
        }
    }

    files.sort();
    Ok(files)
}

struct SqlxQueryVisitor<'a> {
    package_dir: &'a Path,
    queries: Vec<String>,
    error: Option<anyhow::Error>,
}

impl<'a> SqlxQueryVisitor<'a> {
    fn new(package_dir: &'a Path) -> Self {
        Self {
            package_dir,
            queries: Vec::new(),
            error: None,
        }
    }

    fn finish(self) -> anyhow::Result<Vec<String>> {
        if let Some(err) = self.error {
            Err(err)
        } else {
            Ok(self.queries)
        }
    }
}

impl Visit<'_> for SqlxQueryVisitor<'_> {
    fn visit_macro(&mut self, mac: &Macro) {
        if self.error.is_none() {
            match extract_query_text(mac, self.package_dir) {
                Ok(Some(query)) => self.queries.push(query),
                Ok(None) => {}
                Err(err) => self.error = Some(err),
            }
        }

        syn::visit::visit_macro(self, mac);
    }
}

fn extract_query_text(mac: &Macro, package_dir: &Path) -> anyhow::Result<Option<String>> {
    let Some(ident) = mac.path.segments.last().map(|segment| segment.ident.to_string()) else {
        return Ok(None);
    };

    match ident.as_str() {
        "query" | "query_unchecked" | "query_scalar" | "query_scalar_unchecked" => {
            let args: QueryMacroArgs = syn::parse2(mac.tokens.clone()).with_context(|| {
                format!("failed to parse macro arguments for `{ident}!`")
            })?;
            Ok(eval_string_expr(&args.query))
        }
        "query_as" | "query_as_unchecked" => {
            let args: QueryAsMacroArgs = syn::parse2(mac.tokens.clone()).with_context(|| {
                format!("failed to parse macro arguments for `{ident}!`")
            })?;
            Ok(eval_string_expr(&args.query))
        }
        "query_file"
        | "query_file_unchecked"
        | "query_file_scalar"
        | "query_file_scalar_unchecked" => {
            let args: QueryFileMacroArgs = syn::parse2(mac.tokens.clone()).with_context(|| {
                format!("failed to parse macro arguments for `{ident}!`")
            })?;
            Ok(Some(read_query_file(package_dir, &args.path)?))
        }
        "query_file_as" | "query_file_as_unchecked" => {
            let args: QueryFileAsMacroArgs = syn::parse2(mac.tokens.clone()).with_context(|| {
                format!("failed to parse macro arguments for `{ident}!`")
            })?;
            Ok(Some(read_query_file(package_dir, &args.path)?))
        }
        _ => Ok(None),
    }
}

fn read_query_file(package_dir: &Path, path: &LitStr) -> anyhow::Result<String> {
    let query_path = package_dir.join(path.value());
    fs::read_to_string(&query_path)
        .with_context(|| format!("failed to read SQL query file: {}", query_path.display()))
}

fn eval_string_expr(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Lit(ExprLit {
            lit: Lit::Str(lit_str),
            ..
        }) => Some(lit_str.value()),
        Expr::Binary(ExprBinary {
            left,
            op: syn::BinOp::Add(_),
            right,
            ..
        }) => Some(format!("{}{}", eval_string_expr(left)?, eval_string_expr(right)?)),
        Expr::Group(ExprGroup { expr, .. }) | Expr::Paren(ExprParen { expr, .. }) => {
            eval_string_expr(expr)
        }
        _ => None,
    }
}

struct QueryMacroArgs {
    query: Expr,
}

impl Parse for QueryMacroArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let query = input.parse()?;
        let _ = input.parse::<Option<Token![,]>>()?;
        let _rest: TokenStream = input.parse()?;
        Ok(Self { query })
    }
}

struct QueryAsMacroArgs {
    _record: Type,
    query: Expr,
}

impl Parse for QueryAsMacroArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let record = input.parse()?;
        let _comma = input.parse::<Token![,]>()?;
        let query = input.parse()?;
        let _ = input.parse::<Option<Token![,]>>()?;
        let _rest: TokenStream = input.parse()?;
        Ok(Self {
            _record: record,
            query,
        })
    }
}

struct QueryFileMacroArgs {
    path: LitStr,
}

impl Parse for QueryFileMacroArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let path = input.parse()?;
        let _ = input.parse::<Option<Token![,]>>()?;
        let _rest: TokenStream = input.parse()?;
        Ok(Self { path })
    }
}

struct QueryFileAsMacroArgs {
    _record: Type,
    path: LitStr,
}

impl Parse for QueryFileAsMacroArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let record = input.parse()?;
        let _comma = input.parse::<Token![,]>()?;
        let path = input.parse()?;
        let _ = input.parse::<Option<Token![,]>>()?;
        let _rest: TokenStream = input.parse()?;
        Ok(Self {
            _record: record,
            path,
        })
    }
}

async fn fetch_postgres_schema_snapshot(
    ctx: &PrepareCtx<'_>,
) -> anyhow::Result<Option<PostgresSchemaSnapshot>> {
    let Some(database_url) = ctx.connect_opts.database_url.as_deref() else {
        return Ok(None);
    };

    if !is_postgres_url(database_url) {
        return Ok(None);
    }

    let mut conn = crate::connect(ctx.config, &ctx.connect_opts).await?;
    let mut objects = BTreeMap::new();

    let relation_rows = sqlx::query(
        r#"
SELECT
    c.relkind::text AS relkind,
    n.nspname::text AS schema_name,
    c.relname::text AS object_name,
    COALESCE(pg_get_viewdef(c.oid, true), '') AS definition,
    COALESCE(
        string_agg(
            a.attname::text || ':' || pg_catalog.format_type(a.atttypid, a.atttypmod) || ':' || a.attnotnull::int,
            ',' ORDER BY a.attnum
        ) FILTER (WHERE a.attnum > 0 AND NOT a.attisdropped),
        ''
    ) AS columns
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_attribute a ON a.attrelid = c.oid
WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f')
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
GROUP BY c.oid, c.relkind, n.nspname, c.relname
        "#,
    )
    .fetch_all(&mut conn)
    .await?;

    for row in relation_rows {
        let relkind: String = row.try_get("relkind")?;
        let schema_name: String = row.try_get("schema_name")?;
        let object_name: String = row.try_get("object_name")?;
        let definition: String = row.try_get("definition")?;
        let columns: String = row.try_get("columns")?;

        objects.insert(
            format!("relation:{schema_name}.{object_name}"),
            format!("{relkind}|{columns}|{definition}"),
        );
    }

    let function_rows = sqlx::query(
        r#"
SELECT
    n.nspname::text AS schema_name,
    p.proname::text AS object_name,
    pg_get_function_identity_arguments(p.oid) AS identity_args,
    pg_get_function_result(p.oid) AS result_type,
    pg_get_functiondef(p.oid) AS definition
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
        "#,
    )
    .fetch_all(&mut conn)
    .await?;

    for row in function_rows {
        let schema_name: String = row.try_get("schema_name")?;
        let object_name: String = row.try_get("object_name")?;
        let identity_args: String = row.try_get("identity_args")?;
        let result_type: String = row.try_get("result_type")?;
        let definition: String = row.try_get("definition")?;

        objects.insert(
            format!("function:{schema_name}.{object_name}"),
            format!("{identity_args}|{result_type}|{definition}"),
        );
    }

    let type_rows = sqlx::query(
        r#"
SELECT
    n.nspname::text AS schema_name,
    t.typname::text AS object_name,
    t.typtype::text AS type_kind,
    COALESCE(string_agg(DISTINCT e.enumlabel::text, ',' ORDER BY e.enumlabel::text), '') AS enum_labels,
    COALESCE(
        string_agg(
            DISTINCT a.attname::text || ':' || pg_catalog.format_type(a.atttypid, a.atttypmod),
            ',' ORDER BY a.attname::text || ':' || pg_catalog.format_type(a.atttypid, a.atttypmod)
        ) FILTER (WHERE a.attnum > 0 AND NOT a.attisdropped),
        ''
    ) AS attributes
FROM pg_type t
JOIN pg_namespace n ON n.oid = t.typnamespace
LEFT JOIN pg_enum e ON e.enumtypid = t.oid
LEFT JOIN pg_class c ON c.oid = t.typrelid
LEFT JOIN pg_attribute a ON a.attrelid = c.oid
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND t.typtype IN ('e', 'c', 'd')
GROUP BY t.oid, n.nspname, t.typname, t.typtype
        "#,
    )
    .fetch_all(&mut conn)
    .await?;

    for row in type_rows {
        let schema_name: String = row.try_get("schema_name")?;
        let object_name: String = row.try_get("object_name")?;
        let type_kind: String = row.try_get("type_kind")?;
        let enum_labels: String = row.try_get("enum_labels")?;
        let attributes: String = row.try_get("attributes")?;

        objects.insert(
            format!("type:{schema_name}.{object_name}"),
            format!("{type_kind}|{enum_labels}|{attributes}"),
        );
    }

    conn.close().await?;

    Ok(Some(PostgresSchemaSnapshot { objects }))
}

fn is_postgres_url(database_url: &str) -> bool {
    database_url.starts_with("postgres://") || database_url.starts_with("postgresql://")
}

fn extract_sql_dependencies(query: &str) -> BTreeSet<String> {
    let tokens = sql_dependency_tokens(query);
    let mut dependencies = BTreeSet::new();

    let mut i = 0;
    while i < tokens.len() {
        let token = tokens[i].as_str();

        if matches!(token, "from" | "join" | "update" | "into") {
            if let Some((name, next)) = parse_object_name(&tokens, i + 1) {
                dependencies.insert(format!("relation:{name}"));
                i = next;
                continue;
            }
        }

        if token == "delete" && tokens.get(i + 1).is_some_and(|next| next == "from") {
            if let Some((name, next)) = parse_object_name(&tokens, i + 2) {
                dependencies.insert(format!("relation:{name}"));
                i = next;
                continue;
            }
        }

        if token == "truncate" {
            let offset = if tokens.get(i + 1).is_some_and(|next| next == "table") {
                i + 2
            } else {
                i + 1
            };
            if let Some((name, next)) = parse_object_name(&tokens, offset) {
                dependencies.insert(format!("relation:{name}"));
                i = next;
                continue;
            }
        }

        if token == "::" {
            if let Some((name, next)) = parse_object_name(&tokens, i + 1) {
                dependencies.insert(format!("type:{name}"));
                i = next;
                continue;
            }
        }

        if token == "as" {
            if let Some((name, next)) = parse_type_name(&tokens, i + 1) {
                dependencies.insert(format!("type:{name}"));
                i = next;
                continue;
            }
        }

        if is_identifier(token)
            && tokens.get(i + 1).is_some_and(|next| next == ".")
            && tokens.get(i + 3).is_some_and(|next| next == "(")
            && is_identifier(tokens[i + 2].as_str())
        {
            dependencies.insert(format!("function:{}.{}", token, tokens[i + 2]));
            i += 4;
            continue;
        }

        if is_identifier(token)
            && tokens.get(i + 1).is_some_and(|next| next == "(")
            && !FUNCTION_KEYWORDS.contains(&token)
        {
            dependencies.insert(format!("function:{token}"));
            i += 2;
            continue;
        }

        i += 1;
    }

    dependencies
}

const FUNCTION_KEYWORDS: &[&str] = &[
    "array", "cast", "count", "distinct", "exists", "extract", "greatest", "in", "least",
    "over", "position", "substring", "trim", "values",
];

fn sql_dependency_tokens(query: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut chars = query.chars().peekable();

    while let Some(ch) = chars.next() {
        match ch {
            '-' if chars.peek() == Some(&'-') => {
                chars.next();
                for next in chars.by_ref() {
                    if next == '\n' {
                        break;
                    }
                }
            }
            '/' if chars.peek() == Some(&'*') => {
                chars.next();
                let mut prev = '\0';
                for next in chars.by_ref() {
                    if prev == '*' && next == '/' {
                        break;
                    }
                    prev = next;
                }
            }
            '\'' => skip_quoted(&mut chars, '\''),
            '"' => {
                let ident = read_quoted_identifier(&mut chars);
                if !ident.is_empty() {
                    tokens.push(ident.to_lowercase());
                }
            }
            ':' if chars.peek() == Some(&':') => {
                chars.next();
                tokens.push("::".to_string());
            }
            '.' | '(' | ')' | ',' => tokens.push(ch.to_string()),
            c if is_sql_ident_start(c) => {
                let mut ident = String::from(c);
                while let Some(next) = chars.peek().copied() {
                    if is_sql_ident_continue(next) {
                        ident.push(next);
                        chars.next();
                    } else {
                        break;
                    }
                }
                tokens.push(ident.to_lowercase());
            }
            _ => {}
        }
    }

    tokens
}

fn skip_quoted(chars: &mut std::iter::Peekable<std::str::Chars<'_>>, quote: char) {
    while let Some(ch) = chars.next() {
        if ch == quote {
            if chars.peek() == Some(&quote) {
                chars.next();
                continue;
            }
            break;
        }
    }
}

fn read_quoted_identifier(chars: &mut std::iter::Peekable<std::str::Chars<'_>>) -> String {
    let mut ident = String::new();
    while let Some(ch) = chars.next() {
        if ch == '"' {
            if chars.peek() == Some(&'"') {
                ident.push('"');
                chars.next();
                continue;
            }
            break;
        }
        ident.push(ch);
    }
    ident
}

fn parse_object_name(tokens: &[String], start: usize) -> Option<(String, usize)> {
    let first = tokens.get(start)?;
    if !is_identifier(first) {
        return None;
    }
    if tokens.get(start + 1).is_some_and(|next| next == ".") {
        let second = tokens.get(start + 2)?;
        if is_identifier(second) {
            return Some((format!("{first}.{second}"), start + 3));
        }
    }

    Some((first.clone(), start + 1))
}

fn parse_type_name(tokens: &[String], start: usize) -> Option<(String, usize)> {
    let (name, next) = parse_object_name(tokens, start)?;
    if TYPE_KEYWORDS.contains(&name.as_str()) {
        return None;
    }
    Some((name, next))
}

const TYPE_KEYWORDS: &[&str] = &[
    "bigint", "bigserial", "bit", "bool", "boolean", "box", "bytea", "char", "character",
    "cidr", "circle", "date", "decimal", "double", "float", "inet", "int", "int2", "int4",
    "int8", "integer", "interval", "json", "jsonb", "line", "lseg", "macaddr", "money",
    "numeric", "path", "point", "polygon", "real", "serial", "smallint", "text", "time",
    "timestamp", "timestamptz", "timetz", "uuid", "varchar", "void",
];

fn is_identifier(token: &str) -> bool {
    !token.is_empty() && token.chars().all(is_sql_ident_continue)
}

fn is_sql_ident_start(ch: char) -> bool {
    ch == '_' || ch.is_ascii_alphabetic()
}

fn is_sql_ident_continue(ch: char) -> bool {
    is_sql_ident_start(ch) || ch.is_ascii_digit() || ch == '$'
}

/// Find all `query-*.json` files in a directory.
fn glob_query_files(path: impl AsRef<Path>) -> anyhow::Result<Vec<PathBuf>> {
    let path = path.as_ref();
    let pattern = path.join("query-*.json");
    glob::glob(
        pattern
            .to_str()
            .context("query cache path is invalid UTF-8")?,
    )
    .with_context(|| format!("failed to read query cache path: {}", path.display()))?
    .collect::<Result<Vec<_>, _>>()
    .context("glob failed")
}

/// Load the JSON contents of a query data file.
fn load_json_file(path: impl AsRef<Path>) -> anyhow::Result<serde_json::Value> {
    let path = path.as_ref();
    let file_bytes =
        fs::read(path).with_context(|| format!("failed to load file: {}", path.display()))?;
    Ok(serde_json::from_slice(&file_bytes)?)
}

async fn check_backend(config: &Config, opts: &ConnectOpts) -> anyhow::Result<()> {
    crate::connect(config, opts).await?.close().await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::assert_eq;

    #[test]
    fn minimal_project_recompile_action_works() -> anyhow::Result<()> {
        let sample_metadata_path = Path::new("tests")
            .join("assets")
            .join("sample_metadata.json");
        let sample_metadata = std::fs::read_to_string(sample_metadata_path)?;
        let metadata: Metadata = sample_metadata.parse()?;

        let action = minimal_project_recompile_action(&metadata, false, None);
        assert_eq!(
            action,
            ProjectRecompileAction {
                clean_packages: vec![],
                touch_paths: vec![
                    "/home/user/problematic/workspace/b_in_workspace_lib/src/lib.rs".into(),
                    "/home/user/problematic/workspace/c_in_workspace_bin/src/main.rs".into(),
                ],
            }
        );

        Ok(())
    }

    #[test]
    fn eval_string_expr_handles_literal_concat() -> anyhow::Result<()> {
        let expr: Expr = syn::parse_str("\"SELECT \" + \"1\"")?;
        assert_eq!(eval_string_expr(&expr), Some("SELECT 1".to_string()));
        Ok(())
    }

    #[test]
    fn extract_query_text_reads_query_file_macro() -> anyhow::Result<()> {
        let tempdir = tempfile::tempdir()?;
        let sql_path = tempdir.path().join("query.sql");
        fs::write(&sql_path, "select 1")?;

        let mac: Macro = syn::parse_str("query_file!(\"query.sql\")")?;
        assert_eq!(
            extract_query_text(&mac, tempdir.path())?,
            Some("select 1".to_string())
        );
        Ok(())
    }

    #[test]
    fn extract_sql_dependencies_finds_relations_functions_and_types() {
        let deps = extract_sql_dependencies(
            "select lower(u.email)::citext from public.users u join orgs o on o.id = u.org_id where exists(select 1 from audit_log)",
        );

        assert!(deps.contains("relation:public.users"));
        assert!(deps.contains("relation:orgs"));
        assert!(deps.contains("relation:audit_log"));
        assert!(deps.contains("function:lower"));
        assert!(deps.contains("type:citext"));
    }

    #[test]
    fn changed_postgres_objects_matches_unqualified_dependencies() {
        let previous = PostgresSchemaSnapshot {
            objects: BTreeMap::from([(
                "relation:public.users".to_string(),
                "old".to_string(),
            )]),
        };
        let current = PostgresSchemaSnapshot {
            objects: BTreeMap::from([(
                "relation:public.users".to_string(),
                "new".to_string(),
            )]),
        };

        let changed = changed_postgres_objects(&previous, &current);
        assert!(changed.contains("relation:public.users"));
        assert!(changed.contains("relation:users"));
    }
}
